verbose: false

cognito:
  base_url: https://some.auth.us-west-2.amazoncognito.com
  client_id: dummy_id
  client_secret: dummy_secret

auth:
  redirect_uri: https://dummy-host.cloudfront.net/draft/signin
  tmp_session_max_age_sec: 3600
  session_max_age_sec: 86400
  scope: 'openid email'

session:
  cookie_name: sessid
  store:
    region: ap-northeast-1
    table: mysession

